#!/usr/bin/env bash
set -euo pipefail

trap 'echo "FAIL: migration aborted at line $LINENO" >&2' ERR

PYTHON_BIN=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -c "import sys" >/dev/null 2>&1; then
    PYTHON_BIN="$candidate"
    break
  fi
done
if [[ -z "$PYTHON_BIN" ]]; then
  echo "FAIL: python interpreter not available" >&2
  exit 2
fi

SRC=""
OUT=""
VERSION=""
TARGET_VERSION=""
SOURCE_REPOSITORY=""
SOURCE_DOCKER_DOCS=""
SOURCE_COMPOSE_FILE=""

usage(){
  cat <<'USAGE'
usage: migrate-v1-to-v2.sh --src <app-dir> [--out <out-root>] [--version <source-ver>] [--target-version <target-ver>] [--source-repository <url>] [--source-docker-docs <url>] [--source-compose-file <url>]
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --src) SRC="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --target-version) TARGET_VERSION="$2"; shift 2 ;;
    --source-repository) SOURCE_REPOSITORY="$2"; shift 2 ;;
    --source-docker-docs) SOURCE_DOCKER_DOCS="$2"; shift 2 ;;
    --source-compose-file) SOURCE_COMPOSE_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown arg: $1"; usage; exit 2 ;;
  esac
done

[[ -n "$SRC" ]] || { usage; exit 2; }
OUT="${OUT:-/home/node/.openclaw/workspace/artifacts/1panel-apps}"

[[ -d "$SRC" ]] || { echo "FAIL: --src not found: $SRC" >&2; exit 1; }
[[ -s "$SRC/data.yml" ]] || { echo "FAIL: source missing root data.yml" >&2; exit 1; }

APP_KEY=$(awk -F': ' '/^  key:/{print $2; exit}' "$SRC/data.yml" | tr -d '"\r' || true)
[[ -n "$APP_KEY" ]] || APP_KEY="$(basename "$SRC")"
APP_TYPE=$(awk -F': ' '/^  type:/{print $2; exit}' "$SRC/data.yml" | tr -d '"\r' || true)

if [[ -z "$VERSION" ]]; then
  mapfile -t vers < <(find "$SRC" -mindepth 1 -maxdepth 1 -type d ! -name '.*' -printf '%f\n' | sort)
  [[ ${#vers[@]} -eq 1 ]] || { echo "FAIL: multiple version directories, use --version" >&2; exit 1; }
  VERSION="${vers[0]}"
fi

SRC_VER_DIR="$SRC/$VERSION"
[[ -d "$SRC_VER_DIR" ]] || { echo "FAIL: version dir not found: $SRC_VER_DIR" >&2; exit 1; }
[[ -s "$SRC_VER_DIR/docker-compose.yml" ]] || { echo "FAIL: version missing docker-compose.yml" >&2; exit 1; }

TARGET_VERSION="${TARGET_VERSION:-$VERSION}"

APP_DIR="$OUT/$APP_KEY"
VER_DIR="$APP_DIR/$TARGET_VERSION"
mkdir -p "$VER_DIR" "$VER_DIR/data" "$VER_DIR/scripts"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IMAGE=$(awk '/^\s*image:\s*/ {sub(/^\s*image:\s*/, "", $0); gsub(/"/, "", $0); print $0; exit}' "$SRC_VER_DIR/docker-compose.yml" 2>/dev/null || true)
ARCHES=""
if [[ -n "${IMAGE:-}" ]]; then
  ARCHES="$(bash "$SCRIPT_DIR/detect_architectures.sh" "$IMAGE" 2>/dev/null || true)"
fi

cp -f "$SRC/data.yml" "$APP_DIR/data.yml"
[[ -f "$SRC/README.md" ]] && cp -f "$SRC/README.md" "$APP_DIR/README.md" || true
[[ -f "$SRC/logo.png" ]] && cp -f "$SRC/logo.png" "$APP_DIR/logo.png" || true

if [[ ! -f "$APP_DIR/README.md" ]]; then
  cat > "$APP_DIR/README.md" <<MD
# ${APP_KEY}

## 产品介绍

${APP_KEY} 是由 1panel-app-adapter-public 迁移得到的 1Panel 应用。

## 主要功能

- 保持原有应用结构并完成 v2 目录迁移
- 补齐最小可用的版本元数据与脚本

## 访问说明

- 请按 version 目录中的 docker-compose.yml 暴露端口访问

## Introduction

${APP_KEY} is a migrated 1Panel app generated by 1panel-app-adapter-public.

## Features

- v1 to v2 layout migration
- baseline metadata and lifecycle script backfill
MD
fi

if [[ ! -f "$APP_DIR/logo.png" ]]; then
  DEFAULT_LOGO="$SCRIPT_DIR/../assets/default-logo.png"
  if [[ -f "$DEFAULT_LOGO" ]]; then
    cp "$DEFAULT_LOGO" "$APP_DIR/logo.png"
  fi
fi

if [[ -f "$SRC/source-evidence.json" ]]; then
  cp -f "$SRC/source-evidence.json" "$APP_DIR/source-evidence.json"
elif [[ -n "$SOURCE_REPOSITORY" && -n "$SOURCE_DOCKER_DOCS" && -n "$SOURCE_COMPOSE_FILE" ]]; then
  "$PYTHON_BIN" - "$APP_DIR/source-evidence.json" "$SOURCE_REPOSITORY" "$SOURCE_DOCKER_DOCS" "$SOURCE_COMPOSE_FILE" <<'PY'
import json
import sys
from pathlib import Path

out = Path(sys.argv[1])
payload = {
    "repository": sys.argv[2],
    "dockerDocs": sys.argv[3],
    "composeFile": sys.argv[4],
}
out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY
else
  echo "FAIL: source evidence missing. Provide --source-repository --source-docker-docs --source-compose-file or include source-evidence.json in source app" >&2
  exit 1
fi

cp -f "$SRC_VER_DIR/docker-compose.yml" "$VER_DIR/docker-compose.yml"
if [[ -f "$SRC_VER_DIR/data.yml" ]]; then
  cp -f "$SRC_VER_DIR/data.yml" "$VER_DIR/data.yml"
else
  cat > "$VER_DIR/data.yml" <<'YAML'
additionalProperties:
  formFields: []
YAML
fi

[[ -d "$SRC_VER_DIR/data" ]] && cp -a "$SRC_VER_DIR/data/." "$VER_DIR/data/" || true
[[ -d "$SRC_VER_DIR/scripts" ]] && cp -a "$SRC_VER_DIR/scripts/." "$VER_DIR/scripts/" || true

"$PYTHON_BIN" "$SCRIPT_DIR/patch_root_data_yml.py" "$APP_DIR/data.yml" "$APP_KEY" "$ARCHES"
"$PYTHON_BIN" "$SCRIPT_DIR/patch_version_data_yml.py" "$VER_DIR/data.yml"
"$PYTHON_BIN" "$SCRIPT_DIR/patch_compose_yml.py" "$VER_DIR/docker-compose.yml" "$APP_TYPE"
"$PYTHON_BIN" "$SCRIPT_DIR/gen_env_sample.py" "$VER_DIR/data.yml" "$VER_DIR/.env.sample"

if [[ ! -f "$VER_DIR/scripts/init.sh" ]]; then
  cat > "$VER_DIR/scripts/init.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
mkdir -p ./data
SH
  chmod +x "$VER_DIR/scripts/init.sh"
fi

if [[ ! -f "$VER_DIR/scripts/upgrade.sh" ]]; then
  cat > "$VER_DIR/scripts/upgrade.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
exit 0
SH
  chmod +x "$VER_DIR/scripts/upgrade.sh"
fi

if [[ ! -f "$VER_DIR/scripts/uninstall.sh" ]]; then
  cat > "$VER_DIR/scripts/uninstall.sh" <<'SH'
#!/bin/bash
docker-compose down --volumes
SH
  chmod +x "$VER_DIR/scripts/uninstall.sh"
fi

bash "$SCRIPT_DIR/hint-panel-deps.sh" "$VER_DIR/docker-compose.yml" || true
echo "OK: migrated -> $APP_DIR"
